### ISSUE TITLE
rectangle reveal instead of circle

### ISSUE THREAD

**Issue by khazravi** [ozodrukh/CircularReveal#109]
I am using the library for activity transition and I tested it on API 16 and 17 both of them are showing rectangle instead of circle, **but it works properly on API 19**. what should I do to make it work correctly?

**Comment by imknown** [comment]
Though turning off `hardware accelerate` may work, but it blinks...

**Comment by imknown** [comment]
When API <= 18, i recommend you turning off the `hardware accelerated` feature.
> https://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported
