### ISSUE TITLE
Animation under the minSdkVersion="14"

### ISSUE THREAD

**Issue by rty1237ricky** [ozodrukh/CircularReveal#11]
The animation is square instead of round while I set the minSdkVersion="14" in manifest.
I have used the version 1.0.2 but it still didn't work.

**Comment by ozodrukh** [comment]
Hmm, did you try in another version of android? This is only around 14?

I'm tested under 4.1.2, and all goes smooth & round

**Comment by rty1237ricky** [comment]
<uses-sdk
        android:minSdkVersion="14"
        android:targetSdkVersion="21" />

That is my configuration.Unless I delete it that the animation will be round.But I have to use this configuration.

**Comment by ozodrukh** [comment]
Can you provide a video of problem, because i can't repeat this problem

**Comment by rty1237ricky** [comment]
I'm sorry, the video is a little difficult for me. My manifest.xml and the relevant activity(use your CircularReveal in "replaceFragment" method) are sent to your gmail. My project is built in android 5.0.1. However, I suspect that is not the problem of code because your sample.apk of version 1.0.2 run in my phone still show square.

**Comment by asim019** [comment]
This issue is because of hardware Acceleration. when i off hardware acceleration it worked correct but it was too slow. please refer to the following link. 

http://stackoverflow.com/questions/13672802/canvas-clippathpath-not-clipping-as-expected
