### ISSUE TITLE
Dependency to be added

### ISSUE THREAD

**Issue by Alexrs95** [ozodrukh/CircularReveal#12]
Hello,

What is the dependency we should add to our build.gradle in order to use this library? I know I can download the .aar but I can't find the dependency that has been uploaded to Maven Central. 

Thank you in advance!

**Comment by ozodrukh** [comment]
Hello,
There is no dependency in the Maven Central :(
My apologize

**Comment by Alexrs95** [comment]
I will do it. Anyway, it would be great if you could upload it. I have used https://github.com/novoda/bintray-release to upload some libraries to JCenter.

**Comment by ozodrukh** [comment]
can you share information how to create a repository on maven central or jcentral?

**Comment by ozodrukh** [comment]
From Readme.md

```groovy 
    repositories {
        maven {
            url "https://jitpack.io"
        }
    }

  dependencies {
        compile 'com.github.ozodrukh:CircularReveal:(latest-release)@aar'
  }
```
