### ISSUE TITLE
Activity Transtition?

### ISSUE THREAD

**Issue by AruLNadhaN** [ozodrukh/CircularReveal#13]
I want to Apply this Reveal transition to my Activity.
Is it possible to make it as a Activity transition?

**Comment by Curwer** [comment]
No but, you can put the animation code as a method in your activity. Then call on this method after your setContentView. And pass the container view as the argument view.

public class doMagics {
....
setContentView(R.layout.blabla);
LinnearLayout animateThis = (Lin...) findViewById(....)

startSwagAnimation(animateThis);
}

startSwagAnimation(View view) {
//Do your work
}

You might need to modify the animation abit but i know it works.

**Comment by ozodrukh** [comment]
Hi, follow [link](https://halfthought.wordpress.com/2014/12/02/reveal-activity-transitions/), and watch how he implemented reveal transition

**Comment by csbenz** [comment]
Check out this [link](http://frogermcs.github.io/InstaMaterial-concept-part-6-user-profile/) too. It explains very well how to achieve what you want, with all the source code.

**Comment by AruLNadhaN** [comment]
Thanks a lot for the links!
