### ISSUE TITLE
jitpack build of v1.0.3 has error

### ISSUE THREAD

**Issue by tonycn** [ozodrukh/CircularReveal#14]
The animation is great :+1: 
There is build error when I add dependency into my project, 
detail : https://jitpack.io/com/github/ozodrukh/CircularReveal/1.0.3/build.log

**Comment by jitpack** [comment]
Hi! 
The android-maven plugin was missing. Submitted PR #15 to add it.
In the mean time you can try out our forked version:
https://jitpack.io/#jitpack/CircularReveal/1.0.4 : )

If it doesn't work out, please find us on Gitter.
