### ISSUE TITLE
Using this effect with a AlertDialog gives a white background cannot be changed.

### ISSUE THREAD

**Issue by droidekas** [ozodrukh/CircularReveal#18]
I cannot seem to change the white background border which is coming in the alertdialog.Am I doing something wrong here?The clipped view is the grey/black area.I need to make the white background is visible.Is that possible?
![screenshot_2015-03-06-03-53-03](https://cloud.githubusercontent.com/assets/6491284/6515997/a05894a0-c3b4-11e4-9276-6bb56b988d51.png)

**Comment by ozodrukh** [comment]
share your code in the [gist](https://gist.github.com), than i will try to help you

**Comment by droidekas** [comment]
The code is added [here](https://gist.github.com/droidekas/1484eb7903d3d6c09aa1) and I am also facing an issue in lollipop builds.The circular reveal fucntion seems to pick a center which is off the center specified.ie:the animation origin is not from the specified center.

**Comment by Android-s14** [comment]
I have found myself in a similar situation, striving to remove the white background of an underlying view of AlertDialog. I couldn't make it work with AlertDialog and found several opinions that it's impossible, but as a workaround (that I hope you can use as well) I migrated my AlertDialog to android.app.Dialog (which leaves almost all your previous code intact except for the fact there is no builder for Dialog) and used a function to iteratively set transparent background to all parents of the dialog's view. What seems to not work with AlertDialog, works nicely with Dialog.
My dialog creation and xml: [gist](https://gist.github.com/Android-s14/95089628ddd7112a2f35)

**Comment by droidekas** [comment]
Could you find a solution for this?
