### ISSUE TITLE
InvertedCircularReaveal

### ISSUE THREAD

**Issue by cr3ativ3** [ozodrukh/CircularReveal#21]
This is a feature request. When next screen is reveal through circular reveal it would be very convinient and estethicaly pleasing to use inverted reveal when navigating back.

How invertedCircularReveal would work. Circle (with specified centerX, centerY) starts at MAX radius and shrinks to 0 dp or any other end-radius and dissapears, instead of revealing view inside the circle it reveals the view outside of circle's fill area (so the inside of the circle is the 'transaprent area' instead of outside as it is in the regular circle reveal).

**Comment by ozodrukh** [comment]
may be i do not understand, aren't you talking about [this](https://github.com/ozodrukh/CircularReveal/issues/17)

**Comment by cr3ativ3** [comment]
![circular_examlple](https://cloud.githubusercontent.com/assets/7655856/6960662/64734294-d92d-11e4-84f0-08ab9f908c8c.png)
I tried to attack an image what the idea I have in mind.

Top left shows how the animation looks shortly after reveal start. B is the view that was on showing and A is the view being revealed (C is mask scale pivot center).

So with typical reveal you have a opacity mask like on bottom left (white is visible, black is hidden part). While bottom right shows the mask for inverted reveal (again white is the part being revealed, black is hidden a.k.a view underneath)

**Comment by ozodrukh** [comment]
If i understand right, you mean to reveal parent (but, keep child visible, hm it's impossible for now)

Try this one and reveal FrameLayout

```java

<io.codetail.widget.RevealFrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

   <FrameLayout <!-- This layout will made inverting -->
    android:id="@+id/inverted"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

          <android.support.v7.widget.CardView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/awesome_card"
        style="@style/CardView"
        app:cardBackgroundColor="@color/material_deep_teal_500"
        app:cardElevation="2dp"
        app:cardPreventCornerOverlap="false"
        app:cardUseCompatPadding="true"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginTop="8dp"
        android:layout_width="300dp"
        android:layout_height="300dp"
        android:layout_gravity="center_horizontal"
        />

   </FrameLayout>

</io.codetail.widget.RevealFrameLayout>

```

**Comment by cr3ativ3** [comment]
Thanks. I can't run code atm, but will try it back home tonight.
Well if by "keep child visible" you're refering to the top right image, that is not nescessarely then end of animation, B can be as small as 0dp. 

The main difference between this and "reversed circular reveal" you referenced is that view A is being revieald from the sides to some (x, y) center instead of B being hidden. Here, A is on top of B and not the other way arround.

**Comment by cr3ativ3** [comment]
I guess this means feature request was rejected?

**Comment by ozodrukh** [comment]
oops, i thought problem was solved

**Comment by cr3ativ3** [comment]
![animation](https://cloud.githubusercontent.com/assets/7655856/7628921/1a337fa8-fa31-11e4-8079-d69e551a1d0f.gif)

Excuse my photoshop skills, but I tried to make an animation how it would work.
Note that it is not the first screen disapearing, but rather the second screen (email/password) appearing in an inverted fashion.

**Comment by ozodrukh** [comment]
Finally got it, will do my best to implement this feature

**Comment by ozodrukh** [comment]
Hi, well i added reverse feature, check it out in [last version](https://github.com/ozodrukh/CircularReveal/releases), i hope i understood well and did it right, if no please re-open issue

**Comment by sharathyadhav1** [comment]
is there any way to close reveal animation with Drag(using gestures) like snap chat and wats app status
![3d63d530-2723-4556-9f98-e7f26f9b8672](https://cloud.githubusercontent.com/assets/8912909/25937748/e95770f6-363d-11e7-96c0-9e559a32b46d.jpeg)
![c5bb6f9f-5ba3-42ab-acee-afafca533eeb](https://cloud.githubusercontent.com/assets/8912909/25937749/e957e84c-363d-11e7-932f-a82e7b0871ea.jpeg)
