### ISSUE TITLE
Library compatibility

### ISSUE THREAD

**Issue by marbat87** [ozodrukh/CircularReveal#25]
Looking at the code, I didn't find any motivation to keep min compatibility to API 10.
Could you lower it to 9 at least, please?

Thanks in advance.
Regards

**Comment by Saketme** [comment]
Isn't it about time you moved your minimum SDK level to API 14? :)

**Comment by marbat87** [comment]
You're not the first which tell me this thing, but my answer is that thousands people still have Gingerbread (10% of my app users for example) and I cannot ignore them. :(

Regards.

**Comment by ozodrukh** [comment]
Hi, okay, Could you push a pull request ?

**Comment by marbat87** [comment]
Done.

**Comment by marbat87** [comment]
@ozodrukh  Could you also publish a new minor version? thanks in advance.
