### ISSUE TITLE
Touch Events not Intercepted inside Frame & Linear Layouts Pre-L

### ISSUE THREAD

**Issue by tanallnight** [ozodrukh/CircularReveal#28]
I have a circular reveal frame layout which works fine 5.0+ but when testing on a Pre-L device none of the elements inside the frame layout seem to respond to touch events, at first I thought it was an issue with focusing so I intercepted the touch event and disabled the event for the parent and rerouted it to inside the frame layout but it still didnt work.

**Comment by ozodrukh** [comment]
Reveal*Layout doesn't handles any *Touch methods so, issue cannot be depends from the library, or can use provide a little bit more information?

**Comment by tanallnight** [comment]
Here is my XML code, I tried moving the revealview to the end of the framelayout so its drawn last
http://pastebin.com/19TkSUPw

**Comment by ozodrukh** [comment]
i think it cause of RecyclerView, it intercepts listview touch events

**Comment by tanallnight** [comment]
It happened before I added the recyclerView too

**Comment by WasimMemon** [comment]
any update on this issue b'z i am also facing this issue. my recycler view getting touch event even i click on revealframe overlay layout.
