### ISSUE TITLE
Programmatically cancel current animation

### ISSUE THREAD

**Issue by aashrey99** [ozodrukh/CircularReveal#30]
Is there any way to programmatically cancel a running circular reveal animation? Perhaps something like

if (animation.isRunning()) {
    animation.cancel();
}

**Comment by ozodrukh** [comment]
Ok, it is not implemented by API but you can do something like that

```java
  SupportAnimator animator = ...
  if(animator.isRunning()){
     com.nineoldandroid.Animator cna = animator.get();
     cna.cancel();
  }
```

**Comment by aashrey99** [comment]
Sure, thanks! I'll try this for now. Could you add a method to make it easier to access later on?

**Comment by ozodrukh** [comment]
it will be better and faster i you would add pull request

**Comment by ozodrukh** [comment]
checkout [last version](https://github.com/ozodrukh/CircularReveal/releases)
