### ISSUE TITLE
CircularReveal does not have any effect running on Android 5.1

### ISSUE THREAD

**Issue by tounaobun** [ozodrukh/CircularReveal#31]
It is weird that running on Android 5.1,ViewAnimationUtils.createCircularReveal does not have any animation starting.

**Comment by ozodrukh** [comment]
well, it works on my phone furthermore on Genymotion emulator too, can you share any piece of code

**Comment by yhsj0919** [comment]
device: mi2
system: miui6,android5.0.2
createCircularReveal does not have any animation starting.

**Comment by ozodrukh** [comment]
Guys, can you share code that you are running?

**Comment by yhsj0919** [comment]
you can see that it's a old version . you can replace the new code  https://github.com/yhsj0919/YHUtils/tree/master/YHUI

**Comment by marbat87** [comment]
I confirm that it doens't work on Android 5.0 or above (tested on 5.0 and 5.1.1).

My code is the following:
<pre>
                rootView.findViewById(R.id.consegnati_view).setVisibility(View.INVISIBLE);
                View myView = rootView.findViewById(R.id.choose_view);
                myView.setVisibility(View.VISIBLE);

                // get the center for the clipping circle
                int cx = myView.getRight();
                int cy = myView.getTop();

                // get the final radius for the clipping circle
                int finalRadius = Math.max(myView.getWidth(), myView.getHeight());

                SupportAnimator animator =
                        ViewAnimationUtils.createCircularReveal(myView, cx, cy, 0, finalRadius);
                animator.setInterpolator(new AccelerateDecelerateInterpolator());
                animator.setDuration(CIRCLE_DURATION);
                animator.start();
</pre>

The purpose is to hide "consegnati_view" and reveal the "choose_view" from the top right corner. They're inside the same parent "io.codetail.widget.RevealFrameLayout" in my xml.

It works perfectly on Android versions below 5.0

**Comment by ozodrukh** [comment]
marbat87, hm interesting remark, try to figure out today

**Comment by tounaobun** [comment]
@ozodrukh I think the code I wrote is correct,because it runs successfully below Android L.Maybe it is a problem of compatibility.Hope you can fix it.Thanks.:-)

**Comment by ozodrukh** [comment]
Well actually I made a commit relative to this issue, and some sample, cab
you check out them, if everything is fine I will made release it

**Comment by efeturi** [comment]
I'll like to add that it doesn't work for me too 5.0 and 5.1 but works pre-L.

I don't know how to get the fix from github thought.Could you help me

**Comment by ozodrukh** [comment]
Can you clone repository and check out new version (it is not released in jitpack)

**Comment by y3seker** [comment]
I can confirm that last changes working on 5.1.1, thanks for it.

**Comment by ozodrukh** [comment]
Great :+1:  
i'm closing this issue for now, if something happen please re-open it and provide some more information
will wait for 2 day and made release

**Comment by aashrey99** [comment]
When will the update be released?

**Comment by devspacenine** [comment]
Can confirm that version 1.1.1 works on Android 5.1.1. @aashrey99 it is now in jitpack

**Comment by ozodrukh** [comment]
Thanks guys for help :+1:
