### ISSUE TITLE
java.lang.NoClassDefFoundError: io.codetail.animation.RevealAnimator$RevealRadius

### ISSUE THREAD

**Issue by wingoku** [ozodrukh/CircularReveal#32]
I am getting this exception on pre-lollipop devices. Any ideas why? I have imported the library and upon clicking the class name, it takes me to its source code as well.

``` java.lang.NoClassDefFoundError: io.codetail.animation.RevealAnimator$RevealRadius
            at io.codetail.animation.RevealAnimator.<clinit>(RevealAnimator.java:20)
            at io.codetail.animation.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:62)```

**Comment by ozodrukh** [comment]
Hi, Can you provide some more information Device and Code?

**Comment by wingoku** [comment]
Nexus 5 Android 5.1.1


```
                int cx = (v.getLeft() + v.getRight()) / 2;
                int cy = (v.getTop() + v.getBottom()) / 2;

 SupportAnimator anim =
                            io.codetail.animation.ViewAnimationUtils.createCircularReveal(swipifyEnableDisableScreen, cx, cy, 0, maxSize);

                    anim.setDuration(1000);
                    anim.setInterpolator(new AccelerateDecelerateInterpolator());

                    anim.addListener(new SupportAnimator.AnimatorListener() {
                        @Override
                        public void onAnimationStart() {
 
                        }

                        @Override
                        public void onAnimationEnd() {

                        }

                        @Override
                        public void onAnimationCancel() {

                        }

                        @Override
                        public void onAnimationRepeat() {

                        }
                    });

                    anim.start();
```

**Comment by wingoku** [comment]
Any solution?

**Comment by ozodrukh** [comment]
well still not

**Comment by wingoku** [comment]
It can't find the static class. Check your code for generating the .aar file. It might be ignoring the static files when creating jar for .aar

**Comment by scottyab** [comment]
Could it be a jitpack.io issue?

**Comment by esperia** [comment]
I have also same problem.
but, Import directly It worked for me.

1.clone
```sh
$ cd /path/to/your-project
$ git clone https://github.com/ozodrukh/CircularReveal
```

2.`./settings.gradle`
```gradle
include ':app'
include ':CircularReveal:circualreveal' // Add
```

3.`./app/build.gradle`
```gradle
dependencies {
    ...
    compile project(':CircularReveal:circualreveal') // Add
}
```

4.`./CircularReveal/circualreveal/build.gradle`
```gradle
apply plugin: 'com.android.library'
//apply plugin: 'android-maven' // Comment out
...
```

**Comment by ozodrukh** [comment]
looks like jitpack problem

**Comment by wingoku** [comment]
@ozodrukh Can you tell me how can I bundle all the dependencies inside the .aar file. I have no expertise in gradle or groovy. So I can't figure out the exact code that would generate the reference dependencies bundle in .aar file. Currenly I am using following code to generate .aar file which I upload to my server from where other can reference them

```
uploadArchives{
    repositories.mavenDeployer {
        def deployPath = file(getProperty('aar.deployPath'))
        repository(url: "file://${deployPath.absolutePath}")
        pom.project {
            groupId 'myPackageName'
            artifactId 'wingoku-io'
            version "0.0.6"
        }
    }
}
```

**Comment by scottyab** [comment]
@ozodrukh I wrote a how to guide for [publishing to maven](http://intohand.com/blog/post/how-to-publish-your-open-source-library-to-maven-central) central if it helps.

**Comment by wingoku** [comment]
@scottyab it doesn't mention anywhere how to bundle all the referenced dependencies in the .aar file.

**Comment by ozodrukh** [comment]
@wingoku, android it does automatically every time you press on build or run button (only on libraries projects)

**Comment by wingoku** [comment]
In my case it doesn't add SDK dependencies in the App's gradle file. So I want to package all the dependencies in the .aar file.

**Comment by jitpack-io** [comment]
Hi all,
Is there a problem with the latest 'aar' file? If its something on our side then we'll work on fixing it.
The class itself is included in the aar so perhaps its a similar issue to [this one](http://stackoverflow.com/q/28432140/3975649)?

**Comment by BhaveshPatadiya** [comment]
I am still facing this same issue. Any Solution available?

**Comment by sridhar-nalam** [comment]
add library in dependencies without aar extension. It worked for me. 
dependencies {
compile 'com.github.ozodrukh:CircularReveal:1.1.0'
}

**Comment by rahulchowdhury** [comment]
Adding dependencies without @aar worked fine for me as well. Thanks Sridhar :+1:

**Comment by MeenaxiD** [comment]
Yes, adding dependencies without @aar works.

**Comment by ebabel** [comment]
RevealAnimator$RevealRadius is extending FloatProperty, which doesn't exist in android versions prior to 4.0. So this shouldn't work, right? Removing the @aar works for me as well (somehow). Can you remove this from the README.md?

**Comment by lvl4fi4** [comment]
hi i had the same problem on some project that i set new  CircularReveal version in dependencies . i just used old version     compile 'com.github.ozodrukh:CircularReveal:1.0.4'

**Comment by RaghavThakkar** [comment]
Without @aar works.

**Comment by sachithkn** [comment]
works without @aar thankyou.

**Comment by tiveor** [comment]
the same here, working like a charm without @aar, many thanks.

**Comment by robillo** [comment]
working fine with the older version (1.0.4), not working with or without @aar in 2.0.4 version.
