### ISSUE TITLE
Can you provide a SimpleAnimatorListener for SupportAnimator.AnimatorListener

### ISSUE THREAD

**Issue by tounaobun** [ozodrukh/CircularReveal#33]
public abstract class SimpleAnimatorListener implements AnimatorListener {

        @Override
        public void onAnimationStart() {

        }

        @Override
        public void onAnimationEnd() {

        }

        @Override
        public void onAnimationCancel() {

        }

        @Override
        public void onAnimationRepeat() {

        }
    }

which can simply code,cause sometimes I want to override part of the methods,not all of them.

**Comment by ozodrukh** [comment]
Please push me a pull request
