### ISSUE TITLE
Possibility of having RevealRelativeLayout?

### ISSUE THREAD

**Issue by sidhantpanda** [ozodrukh/CircularReveal#40]
This would allow to have custom attributes like "layout_below" for custom views which extend RevealRelativeLayout.

In my case, I have a custom view extending RevealFrameLayout with 2 or 3 children and their alignment depends on a particular root view element (which is the custom view's sibling). Both the custom view and the sibling are in a RelativeLayout.

**Comment by ozodrukh** [comment]
You can make custom view, but anyway must have feature, i will add it soon

**Comment by ozodrukh** [comment]
Using Composition by extending RevealViewGroup adds possibility to extend any view with no pain
