### ISSUE TITLE
Not working on Lollipop

### ISSUE THREAD

**Issue by MajeurAndroid** [ozodrukh/CircularReveal#41]
On lollipop devices, RevealFrameLayout isn't filled, children inside it aren't visibles. Therefore it works well on pre-lollipop devices, but I had to remove the **"@aar"** from the dependency to get it functional.

```java
    int cx = (view.getLeft() + view.getRight()) / 2;
    int cy = (view.getTop() + view.getBottom()) / 2;
    int h = view.getHeight();
    int w = view.getWidth();

    int finalRadius = (int) Math.sqrt(h * h + w * w);

    SupportAnimator animator =
            ViewAnimationUtils.createCircularReveal(view, cx, cy, 0, finalRadius);
    animator.start();
```

**Comment by ozodrukh** [comment]
checkout this (issue)[https://github.com/ozodrukh/CircularReveal/issues/31]

**Comment by MajeurAndroid** [comment]
Oh sorry, so I have to clone and import lib as project manually ? Do you manage to update jetbrain version ?

**Comment by ozodrukh** [comment]
No, no need to import project manually, try this
`compile 'com.github.ozodrukh:CircularReveal:1.1.1@aar'`
