### ISSUE TITLE
Failed to resolve library dependency

### ISSUE THREAD

**Issue by Shnkc** [ozodrukh/CircularReveal#42]
```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion '22.0.1'

    defaultConfig {
        applicationId "com.example.app"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.github.ozodrukh:CircularReveal:1.1.0'

}
```
I've got following error.

```Error:(31, 13) Failed to resolve: com.github.ozodrukh:CircularReveal:1.1.0```

My gradle version : 1.2.3

Is there a problem on dependency?

**Comment by mooncafes** [comment]
add repo url to gradle, it will work fine. 

repositories {
        maven {
            url "https://jitpack.io"
        }
    }

**Comment by vipulasri** [comment]
Please add this portion 

repositories {
maven {
url "https://jitpack.io"
}
}

and 
rename : 
compile 'com.github.ozodrukh:CircularReveal:1.1.0'
to 
compile 'com.github.ozodrukh:CircularReveal:1.1.1@aar'

**Comment by Shnkc** [comment]
Thanks, it worked.
