### ISSUE TITLE
Cannot execute apk

### ISSUE THREAD

**Issue by codeismine** [ozodrukh/CircularReveal#43]
Hi,

I am getting below error when I am trying to run the apk. Please note build is happening fine.

Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.

> java.util.zip.ZipException: duplicate entry: io/codetail/widget/RevealLinearLayout.class

**Comment by ozodrukh** [comment]
looks like one of your dependencies already using my library

**Comment by codeismine** [comment]
Problem is that if I dont use your library than the app is crashing on devices which are less than lollipop so I am not sure if that is the case. PFA my gradle file. Can you make out which library that might be? And what can be the solution so that I can use your library. Thanks in advance.
![gradle](https://cloud.githubusercontent.com/assets/11025037/9149538/db24e9f2-3dcc-11e5-8830-e02d176f78b2.png)

**Comment by ozodrukh** [comment]
https://github.com/gowong/material-sheet-fab this dependency is using my library, 
u need to add exclude on that library and append mine (if u don't know how to add exclude please google it, a lot of examples are available on StackOverFlow)

**Comment by codeismine** [comment]
Hi thanks for the information. I have tried following line but somehow it is not working, please correct me if I am wrong somewhere:

compile('com.gordonwong:material-sheet-fab:1.0.1')
            {
                exclude module: 'com.github.ozodrukh'
            }

I also tried  exclude group: 'com.github.ozodrukh'

**Comment by ozodrukh** [comment]
```groovy
compile('com.gordonwong:material-sheet-fab:1.0.1'){
  exclude module: 'CircularReveal'
}
```

**Comment by codeismine** [comment]
Unfortunately I am getting same error even after writing above code in gradle.

Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: io/codetail/widget/RevealLinearLayout.class

**Comment by codeismine** [comment]
I have added exclude module: 'CircularReveal' to few more libraries on which I had doubt but still no luck. PFA screenshot
![exclude_circular_2](https://cloud.githubusercontent.com/assets/11025037/9175615/42c84ac6-3fa4-11e5-815a-993bac78f032.png)

**Comment by codeismine** [comment]
Will highly appreciated you if you could tell me some workaround. Thanks
