### ISSUE TITLE
Want to use Library  for fragment transition 

### ISSUE THREAD

**Issue by shiprasinghal1** [ozodrukh/CircularReveal#45]
Hey , please guide me . I want to put this animation(circular reveal) for fragment transitions . But really confused on part how to do it ?

**Comment by imidhuntv** [comment]
@shiprasinghal1 Did you find any solution?

**Comment by ozodrukh** [comment]
there is no possibility to use it in fragment transition, i provided simple example how to do start animation, take a look in sample
