### ISSUE TITLE
opening activity with reveal?

### ISSUE THREAD

**Issue by TheLoyalCruel** [ozodrukh/CircularReveal#50]
is it possible to open an activity with reveal?

**Comment by Alxzu** [comment]
Hi, did you solve this? I'm trying to do the same here

**Comment by LeonardoCardoso** [comment]
Maybe this repo [FabTransitionActivity](https://github.com/coyarzun89/FabTransitionActivity) will work for you. It's fork of this repo.

**Comment by Alxzu** [comment]
Thanks, that work just great!!

Date: Sat, 21 Nov 2015 11:05:30 -0800

**Comment by LeonardoCardoso** [comment]
@Alxzu Great, can you close this issue then?

**Comment by Alxzu** [comment]
I didn't open this issue, can I close it anyway?

**Comment by LeonardoCardoso** [comment]
@Alxzu my bad! :smile: 
@TheLoyalCruel can you close it?!

**Comment by TheLoyalCruel** [comment]
@LeonardoCardoso thanks for this library...
but it's just for fab! I want to open all of my activities with reveal and close them with reveal!
is it possible?

**Comment by LeonardoCardoso** [comment]
@TheLoyalCruel You can just call mSheetLayout.expandFab(), it has this name, but you don't need to have a visible FAB though. Then your layout will be expanded, and with the listener implemented you can call you activity when it ends.

**Comment by TheLoyalCruel** [comment]
can we call several activities? or just one?

**Comment by LeonardoCardoso** [comment]
@TheLoyalCruel how do you by calling several activities? You can call only one at once, but as many as you want if nesting them.
