### ISSUE TITLE
FPS drops when using AdMob ads

### ISSUE THREAD

**Issue by saibbyweb** [ozodrukh/CircularReveal#52]
Reveal animation works buttery smooth. But when I integrated Google AdMob ads into my app, reveal animation became buggy? Worst part is, Ads are integrated in one activity and reveal animation is implemented in another activity, yet it becomes unstable. I tried banner ads only.

**Comment by saibbyweb** [comment]
*banner ads only.

**Comment by saibbyweb** [comment]
*real animation = reveal animation

**Comment by danielhickman** [comment]
P.S. You can edit you comments.

**Comment by ozodrukh** [comment]
duplicate #51
