### ISSUE TITLE
Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory

### ISSUE THREAD

**Issue by nhjariwala** [ozodrukh/CircularReveal#56]
Just try to import Source Code 1.1.1 and got the error. Dont know what's going wrong with it but it showing error on

![screen shot 2015-11-05 at 12 17 19 pm](https://cloud.githubusercontent.com/assets/11612197/10961682/548dbe88-83b7-11e5-8414-91b03a058c3b.png)

While clicking on Open File it redirect to build.gradle. Please have look it.

apply plugin: 'com.android.library'
apply plugin: 'android-maven'

    android {
      compileSdkVersion 22
       buildToolsVersion "22.0.1"

         defaultConfig {
            minSdkVersion 9
             targetSdkVersion 22
       }
     }
    dependencies {
      compile 'com.nineoldandroids:library:2.4.0'
    }

Thanks in advance

**Comment by djvsal** [comment]
If you want to use gradle 2.4.0, you should config android-maven-plugin version to 1.3 in classpath in the project root build.gradle as :


com.github.dcendents:android-maven-gradle-plugin:1.3

**Comment by nhjariwala** [comment]
Hi @djvsal thanks for your response. Sorry i didn't get you as I am beginner in Android Studio. Can you please give me some more hint or code or snippet would be great.

**Comment by ozodrukh** [comment]
updated project, fixed issue

**Comment by apurvaaggarwal** [comment]
apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: 'com.jfrog.bintray'

version = "1.1.0"
group = "com.github.boxme"

def siteUrl = 'https://github.com/boxme/SquareCamera'
def gitUrl = 'https://github.com/boxme/SquareCamera.git'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    resourcePrefix "squarecamera__"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 5
        versionName "1.1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE.txt'
    }
}

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())

bintray {
    user = properties.getProperty("bintray.user")
    key = properties.getProperty("bintray.apikey")

    configurations = ['archives']
    pkg {
        repo = "maven"
        name = "SquareCamera"
        websiteUrl = siteUrl
        vcsUrl = gitUrl
        licenses = ["MIT"]
        publish = true
    }
}

install {
    repositories.mavenInstaller {
        pom {
            project {
                packaging 'aar'
                name 'A camera that takes square photos'
                url siteUrl
                licenses {
                    license {
                        name 'The MIT License'
                        url 'https://github.com/boxme/SquareCamera/blob/master/LICENSE'
                    }
                }
                developers {
                    developer {
                        id 'boxme'
                        name 'Desmond Ng'
                        email 'desmond.ng.yang.yi@gmail.com'
                    }
                }
                scm {
                    connection gitUrl
                    developerConnection gitUrl
                    url siteUrl

                }
            }
        }
    }
}

repositories {
    maven {
        url "http://dl.bintray.com/populov/maven"
    }
    mavenCentral()
    mavenLocal()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:support-v4:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'com.google.android.gms:play-services:8.4.0'
}

task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives javadocJar
    archives sourcesJar
}



I have the same error
I am unable to solve it ,please help me out?

**Comment by cnmao** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.github.dcendents:android-maven-plugin:1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

please ？？？
