### ISSUE TITLE
animating children during a circular reveal

### ISSUE THREAD

**Issue by mariuspena** [ozodrukh/CircularReveal#57]
Hi

I was animating a viewA (inside a RevealFrameLayout) with 
SupportAnimator anim = io.codetail.animation.ViewAnimationUtils.createCircularReveal(viewA, cx, cy, 0, finalRadius);
after anim.start() I was also animating some children inside viewA (simple fade).

Since android 6 the fade of the children does not work anymore. If I test it in a simulator on android <6 it works. 

do you know anything about it ?

**Comment by ozodrukh** [comment]
No, i'm sorry, i didn't tested 6.0 yet
