### ISSUE TITLE
animator.start() fires listener, but animator.reverse().start() does not

### ISSUE THREAD

**Issue by yonatancups** [ozodrukh/CircularReveal#60]
If you set a listener on the supportanimator and then call start() everything works fine. If, however, you call supportanimator.reverse().start() then the listener does not fire *at all*. If you call reverse() and then open a new line and call start() it works properly. 

supportanimator.reverse().start() -> doesn't work

supportanimator.reverse();
supportanimator.start(); -> works

**Comment by ozodrukh** [comment]
reverse just generates reversed version animator object, thats all, it doesn't copies any attributes of original, so you have to setup it by yourself again
