### ISSUE TITLE
Remove NineOldsAndroid dependency?

### ISSUE THREAD

**Issue by renaudcerrato** [ozodrukh/CircularReveal#63]
IMO, anything supporting below API 14 is a waste of time and resources - NineOldsAndroid dependency could be removed and save us thousands of method calls and kilobytes..

**Comment by ozodrukh** [comment]
Yes it is, i will try to take time this week , and modify the library

**Comment by renaudcerrato** [comment]
I did it already a few times ago - but not sure if it up-to-date:

https://github.com/renaudcerrato/CircularReveal

**Comment by ozodrukh** [comment]
can you send pull request?

**Comment by renaudcerrato** [comment]
https://github.com/ozodrukh/CircularReveal/pull/64

**Comment by ozodrukh** [comment]
Fixed

**Comment by renaudcerrato** [comment]
Thanks!


ᐧ
