### ISSUE TITLE
java.lang.NoSuchMethodError: io.codetail.animation.SupportAnimator.setDuration

### ISSUE THREAD

**Issue by sunnystatue** [ozodrukh/CircularReveal#67]
Hi,

calling mFabToolbar.expandFab(); on pre lollipop device, causes following exception:

java.lang.NoSuchMethodError: io.codetail.animation.SupportAnimator.setDuration at com.bowyer.app.fabtoolbar.FabToolbar.expandPreLollipop(FabToolbar.java:368) at com.bowyer.app.fabtoolbar.FabToolbar.expandFab(FabToolbar.java:241) at com.shygunsys.mu.cybermobile.ui.MainActivityFragment$1.onClick(MainActivityFragment.java:61)

**Comment by siddlv** [comment]
change

```
compile ('com.github.ozodrukh:CircularReveal:1.3.1@aar') {
        transitive = true;
    }
```
to

```
compile ('com.github.ozodrukh:CircularReveal:1.1.1@aar') {
        transitive = true;
    }
```
new version of the library causes problems on Pre Lollipop Devices for some reasons (which I too don't know)
