### ISSUE TITLE
 Failed to resolve: com.github.ozodrukh:CircularReveal:1.3.1

### ISSUE THREAD

**Issue by drduan** [ozodrukh/CircularReveal#68]
Error:(87, 14) Failed to resolve: com.github.ozodrukh:CircularReveal:1.3.1
<a href="openFile:/Users/dua/Documents/ClassDemo/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by drduan** [comment]
in android studio

**Comment by samdarcy42** [comment]
Try adding this to your Gradle:

repositories {
    maven {
        url "https://jitpack.io"
    }
}

Fixed the issue for me!

**Comment by gianpaolodn** [comment]
I have the same issue after upgrading gradle to version 2.10.
Solved manually downloading gradle 2.12

**Comment by spaceisstrange** [comment]
Make sure you don't have the "Offline work" option checked on _Build, Execution Deployment -> Gradle_ under settings.

<img width="1149" alt="captura_de_pantalla_2016-07-28_a_las_3_24_16" src="https://cloud.githubusercontent.com/assets/6024783/17198194/a4b6e9ec-5473-11e6-9af3-a65c223a0902.png">

**Comment by hiteshsahu** [comment]
I am facing same issue. I am using this in android library , in which gradle am I supposed to add 

```
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```
