### ISSUE TITLE
Request - Decrease API Version To 14

### ISSUE THREAD

**Issue by TurKurT656** [ozodrukh/CircularReveal#69]
hi,
This is an amazing Library.
I think the minimum sdk version of this lib can be reduce to version 14 without problem.

if there is that posibility i will be thankful if  you do that.

Sorry for bad english

**Comment by daniele-athome** [comment]
Actually repo description says 2.3+, would you mind changing it as well as it's misleading now?

**Comment by AkaOne** [comment]
Yup this must be changed...

**Comment by Rygelouv** [comment]
I agree.

**Comment by ozodrukh** [comment]
Done!
