### ISSUE TITLE
Know if children are revealed and are they drawn?

### ISSUE THREAD

**Issue by vpratfr** [ozodrukh/CircularReveal#71]
Hi,

I have a FrameLayout which contains a List and a RevealLayout with a MapView inside. When pressing a button, I reveal/hide the MapView.

I have 2 questions:
- Is there a way to know if the MapView is currently fully hidden or do I have to keep track of this with a boolean for instance?
- When not revealed, is the MapView drawn or is it completly ignored?

**Comment by vpratfr** [comment]
Bug linked to MapView being more or less a surface view. I worked around that by setting a solid background on the layout behind the MapView, and showing the MapView only once the reveal animation is done.

Still, two questions left:

- State is not persisted : the layout should keep track of its current reveal radius and save that state (e.g. when device screen rotates)
- There should be a way to directly set the reveal radius without animating it. Currenty that give NullPointerException as no default RevealInfo is created without animator.

**Comment by ozodrukh** [comment]
Hi,
Now on i have rewritten code once again, as experience rise, i decided to rewrite my messy code, can we collaborate in order to add persisted state
I have changed API you can set radius directly without animation triggering

**Comment by ozodrukh** [comment]
1. To keep tracking of View state is simple set `View.GONE` before animation is started and set it to `View#VISIBLE` on `onAnimationStart(Animator)`

2. When View is not revealed means radius 0? then it clipped by the Canvas all calls of view drawing should be ignore :)

3. Currently as i know Android doesn't persist animations states, therefore this animation also shouldn't 😅

4. Yeah there is still no way to do it manually, except extending ViewRevealManager and adding this feature manually

5. Using `ViewRevealManager.isClipped(View)` you can get to know whether view is clipped
