### ISSUE TITLE
make reveal animation from screen edges

### ISSUE THREAD

**Issue by LloydBlv** [ozodrukh/CircularReveal#81]
Thanks for the great library, I was wondering if there's way to make the reveal animation from all edges of screen to the center point? consider it as a wave coming from four edges of screen closing in the center of screen!
thanks again! @ozodrukh

**Comment by ozodrukh** [comment]
Yeah, create `RevealFrameLayout` with 4 cards and start all animations same times with different start locations
e.g
```java 
ViewAnimationUtils.createCircularReveal(yourCard, left, top, 0, endRadius);
ViewAnimationUtils.createCircularReveal(yourCard, right, top, 0, endRadius);
ViewAnimationUtils.createCircularReveal(yourCard, left, bottom, 0, endRadius);
ViewAnimationUtils.createCircularReveal(yourCard, right, bottom, 0, endRadius);

AnimatorSet reveals = new AnimatorSet();
// ... add those animators and setup AnimatorsSet
reveals.start()
```
