### ISSUE TITLE
RevealLinearLayout under AppBarLayout

### ISSUE THREAD

**Issue by juliender** [ozodrukh/CircularReveal#82]
Hi, 

one of my users, with nexus 5X, android 6.0.1, has the `RevealLinearLayout` 

with is displayed under the `AppBarLayout`
![screenshot_20160510-095618](https://cloud.githubusercontent.com/assets/4390660/15146062/8444e9e0-16b9-11e6-9cf6-d5b63ee82944.png)

is it code related ? I dont really understand (it's only one user, no big deal)

      <?xml version="1.0" encoding="utf-8"?>
     <android.support.design.widget.CoordinatorLayout  
 mlns:android="http://schemas.android.com/apk/res/android"
          xmlns:app="http://schemas.android.com/apk/res-auto"
          xmlns:tools="http://schemas.android.com/tools"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:fitsSystemWindows="true"
          tools:context="com.xxxx.android.EntryActivity">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            app:theme="@style/ThemeOverlay.AppCompat.ActionBar"
            >

            
                
                
                
                
                
                

            <TextView
                android:id="@+id/title"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textColor="@color/white"
                android:textSize="20dp"
                android:text="Quoi de neuf"
                android:layout_marginLeft="16dp"
                android:layout_marginBottom="8dp"/>

        </android.support.v7.widget.Toolbar>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tabGravity="fill"
            app:tabIndicatorHeight="4dp"
            style="@style/MyCustomTabLayout"
            />

    </android.support.design.widget.AppBarLayout>

    <include layout="@layout/content_entry" />

    <View
        android:id="@+id/dim_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:alpha="0"
        android:background="@color/alpha_black"
        android:elevation="4dp" />
    <include layout="@layout/searchbar" />

    </android.support.design.widget.CoordinatorLayout>

and the searchbar.xml
<?xml version="1.0" encoding="utf-8"?>

    <io.codetail.widget.RevealLinearLayout
     xmlns:android="http://schemas.android.com/apk/res/android"
     android:layout_width="match_parent"
     android:layout_height="wrap_content"
     android:layout_alignParentRight="true"
     android:layout_marginLeft="16dp"
     android:layout_marginRight="16dp"
     android:layout_marginTop="16dp"
     android:elevation="4dp"
     android:orientation="vertical"
     android:id="@+id/reveal_layout"
     >

    <LinearLayout
        android:id="@+id/awesome_one"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        android:clickable="true"
        android:orientation="vertical"
        android:visibility="invisible">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <AutoCompleteTextView
                android:id="@+id/where_field"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@android:color/transparent"
                android:drawableLeft="@drawable/ic_place"
                android:drawablePadding="8dp"
                android:gravity="center_vertical"
                android:padding="16dp"
                android:imeOptions="actionNext"
                android:hint="@string/search_engine_where_placeholder"
                android:singleLine="true"
                android:layout_toLeftOf="@+id/autocomplete_clear_where"
                android:layout_toStartOf="@+id/autocomplete_clear_where"
                android:layout_alignParentEnd="true">
            </AutoCompleteTextView>

            <ImageButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/autocomplete_clear_where"
                android:src="@drawable/ic_close"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"
                android:background="@android:color/white"
                android:padding="5dp"
                android:layout_marginRight="10dp"
                android:visibility="invisible"/>
        </RelativeLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:background="@android:color/darker_gray" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <AutoCompleteTextView
                android:id="@+id/what_field"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@android:color/transparent"
                android:popupBackground="@android:color/white"
                android:drawableLeft="@drawable/ic_work"
                android:drawablePadding="8dp"
                android:gravity="center_vertical"
                android:hint="@string/search_engine_what_placeholder"
                android:padding="16dp"
                android:imeOptions="actionSearch"
                android:singleLine="true"
                android:layout_toLeftOf="@+id/autocomplete_clear"
                android:layout_toStartOf="@+id/autocomplete_clear"
                android:layout_alignParentEnd="true" />

            <ImageButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/autocomplete_clear"
                android:src="@drawable/ic_close"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"
                android:background="@android:color/white"
                android:padding="5dp"
                android:layout_marginRight="10dp"
                android:visibility="invisible" />
        </RelativeLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:background="@android:color/darker_gray"
            android:visibility="invisible" />

    </LinearLayout>

    </io.codetail.widget.RevealLinearLayout>

**Comment by ozodrukh** [comment]
i guess it because it's wrapped under CoordinatorLayout (by default it behaves like frame layout) therefore it's under your Toolbar, you may specify margins or try to inspect it using [Facebook Stetho](http://github.com/facebook/stetho)

**Comment by juliender** [comment]
Thanks, 

I changed `RevealLinearLayout` elevation to 6dp and it works
