### ISSUE TITLE
Log https://jitpack.io/com/github/ozodrukh/CircularReveal/2.0.0/build.log

### ISSUE THREAD

**Issue by PeeJWeeJ** [ozodrukh/CircularReveal#85]
Log https://jitpack.io/com/github/ozodrukh/CircularReveal/2.0.0/build.log

**Comment by ozodrukh** [comment]
Hi, yep i didn't installed repository, will do it tonight

**Comment by 4chill3s** [comment]
Nice ty :)

**Comment by ozodrukh** [comment]
@4chill3s There is an issue with jitpack

**Comment by ozodrukh** [comment]
Works now :)
