### ISSUE TITLE
No reverse() in v2.0.1

### ISSUE THREAD

**Issue by mohakapt** [ozodrukh/CircularReveal#88]
Hi, I just updated to version 2.0.1, looks like reverse() has been removed in this version.
It is possible to reverse animation in this new version?

**Comment by ozodrukh** [comment]
No noway, only manually by reversing values

**Comment by amanzan** [comment]
If I may ask, what's the point of removing reverse() method?

**Comment by ozodrukh** [comment]
@amanzan Previous implementation was really poor and confusing, I decided to remove it,im sorry for inconvenience 😔

**Comment by amanzan** [comment]
No problem, I'm using that method and it has been working just fine so far. I'm sure I'll find an alternative with this new version when I decide to upgrade. Thanks so much for this library, by the way 👍 :)

**Comment by ozodrukh** [comment]
@amanzan Thank you for support 😉 well you can look how it was implemented before in commit history

**Comment by tux-world** [comment]
@amanzan hi man, you was in here :+1:  i have simple quastion whats this below code eqivalent on new version of this library:

```
SupportAnimator animator =
                            ViewAnimationUtils.createCircularReveal(mRevealView, cx, cy, 0, radius);
                    animator.setInterpolator(new AccelerateDecelerateInterpolator());
                    animator.setDuration(800);

                    SupportAnimator animator_reverse = animator.reverse();

                    if (hidden) {
                        mRevealView.setVisibility(View.VISIBLE);
                        animator.start();
                        hidden = false;
                    } else {
                        animator_reverse.addListener(new SupportAnimator.AnimatorListener() {
                            @Override
                            public void onAnimationStart() {

                            }

                            @Override
                            public void onAnimationEnd() {
                                mRevealView.setVisibility(View.INVISIBLE);
                                hidden = true;

                            }

                            @Override
                            public void onAnimationCancel() {

                            }

                            @Override
                            public void onAnimationRepeat() {

                            }
                        });
                        animator_reverse.start();

                    }
```

Thanks

**Comment by Spotik** [comment]
@ozodrukh could u make a gist with the implementation to reverse? Or just reverse the values rly work?

**Comment by ozodrukh** [comment]
Well on _Lollipop_ and higher where native animation is used, it looks like you don't have reverse ability.

By using compat version _(Pre Lollipop)_ cast it to ValueAnimator and use one of this methods 

1. [ValueAnimator.setRepeatMode()](https://developer.android.com/reference/android/animation/ValueAnimator.html#setRepeatMode(int))
2. [ValueAnimator.reverse()](https://developer.android.com/reference/android/animation/ValueAnimator.html#reverse())

**Comment by pedrosoares** [comment]
My reverse i do in this way:
Animator animator = ViewAnimationUtils.createCircularReveal(attachmentLayout, cx, cy, 0, radius);
Animator animatorReverse = ViewAnimationUtils.createCircularReveal(attachmentLayout, cx, cy, radius, 0);
