### ISSUE TITLE
Circular Reveal is Square Reveal!

### ISSUE THREAD

**Issue by Manhazito** [ozodrukh/CircularReveal#89]
I just tested the demo application, and the reveals are squared and not circular.
My device is running API 17, and I'm using Android Studio 2.2 Preview 3 (build tools version is 23.0.3).

**Comment by Manhazito** [comment]
I had to disable Hardware Acceleration on the Activity. It's now working fine! =)

Great library!

**Comment by ozodrukh** [comment]
Phew, i really scared of this issue 😅
