### ISSUE TITLE
YouTube video playback stopped due to unauthorized overlay on top of player

### ISSUE THREAD

**Issue by anantshah93** [ozodrukh/CircularReveal#95]
YouTube video playback stopped due to unauthorized overlay on top of player while using this library.

see detail log:
YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is obscured by io.codetail.widget.RevealFrameLayout{a13189d V.E...... ........ 0,112-720,1022}. YouTubePlayerView is completely covered, with the distance in px between each edge of the obscuring view and the YouTubePlayerView being: left: 30, top: 504, right: 30, bottom: 26..

**Comment by adnbsr** [comment]
What is the relation with this repo?

**Comment by anantshah93** [comment]
When we use this library it stays invisible so youtube player detects it as overlay. But i handled condition to solve it. So you can close this issue.
